class InvalidDataException(Exception):
    pass


class ProcessingException(Exception):
    pass


def check_age(age):
    try:
        if not 1 < int(age) < 110:
            raise InvalidDataException("Некорректный возраст")
        return "Ваш возраст:", age
    except ValueError as ve:
        return (f"Введены некорректные данные {ve}")
    except InvalidDataException as e:
        print(f'Сработало исключение {e}')
        return (f"{age} - Некорректный возраст")
    else:
        print(f'Сработало исключение ProcessingException')
        raise ProcessingException('Значение а - строка')
        return ("Введены некорректные данные")
        # raise
    # else:
    #     return ("Непредвиденная ситуация, ФОРС-МАЖОР")
    finally:
        print('Выходим из функции')
        print()


print(check_age(50))
print(check_age(100))
print(check_age(200))
print(check_age(0))
print(check_age('0'))
print(check_age('fifty'))
